# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('addresses', '0002_auto_20181014_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='billing_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile'),
        ),
    ]
