# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_billing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Billing'), ('professional', 'Professional')], default='billing', max_length=120),
        ),
    ]
