# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_professionalprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
