# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_auto_20181014_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='speciality',
            field=models.IntegerField(choices=[(1, 'Dental'), (2, 'Vision'), (3, 'Physical'), (4, 'Psychological')], default=1),
        ),
    ]
