# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_auto_20181014_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
    ]
