# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0007_auto_20181014_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='address_line_1',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='country',
            field=models.CharField(default='Canada', max_length=120),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='postal_code',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='state',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
