# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-20 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_address_address_type'),
        ('professionals', '0014_auto_20181015_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='professionalprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='professional_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
        ),
    ]
