# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-20 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0015_auto_20181020_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalprofile',
            old_name='professional_address',
            new_name='address',
        ),
    ]
