# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0017_professionalprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalprofile',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
