# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[(1, 'Dental'), (2, 'Vision'), (3, 'Physical'), (4, 'Psychological')], default=1, max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=120, max_digits=10)),
            ],
        ),
    ]
