# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181014_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Dental'), (2, 'Vision'), (3, 'Physical'), (4, 'Psychological')], default=1),
        ),
    ]
