# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181014_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.CharField(choices=[('dental', 'Dental'), ('vision', 'Vision'), ('physical', 'Physical'), ('psychological', 'Psychological')], default='dental', max_length=120),
        ),
    ]
